### PR TITLE
Update to BCC New Open Data Platform

### PR DESCRIPTION
**Pull request by monkee52**
BCC changed open data providers in June 2024. This pull request updates the integration to work with the new API.

### CODE REVIEW

**Comment by Jarimu** [comment]
Hi this is not working for me, copied in the changed files and getting these errors:
Logger: custom_components.bne_wc.sensor
Source: custom_components/bne_wc/sensor.py:293
integration: bne_wc ([documentation](https://github.com/mark1foley/Brisbane-Bin-Day-Sensor), [issues](https://github.com/mark1foley/Brisbane-Bin-Day-Sensor/issues))
First occurred: 8:02:38 PM (2 occurrences)
Last logged: 8:02:39 PM

Error retrieving collection week dataset: ODSQLError: ODSQL query is malformed: Invalid date to parse 10/06/2024: time data '10/06/2024' does not match format '%Y/%m/%d'. Clause(s) containing the error(s): where.

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:580
integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 8:02:39 PM (2 occurrences)
Last logged: 8:02:39 PM

Error adding entity sensor.brisbane_bin_day for domain sensor with platform bne_wc
Error adding entity sensor.brisbane_bin_day_recycle for domain sensor with platform bne_wc

**Comment by Jarimu** [comment]
Ignore that, pulled the original version and saw that you had made update for fixing the extra bin date

**Comment by mark1foley** [comment]
Hi,

I have merged in the changes from provided by Ayden and published a new version.

Should work now.

Mark

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mark1foley** [comment]
Hi,

Thank for doing this.  I have merged in you changes and published the new version.

Mark

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Ayden ***@***.***>
Sent: Tuesday, June 11, 2024 6:30:15 PM
To: mark1foley/Brisbane-Bin-Day-Sensor ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mark1foley/Brisbane-Bin-Day-Sensor] Update to BCC New Open Data Platform (PR #1)


BCC changed open data providers in June 2024. This pull request updates the integration to work with the new API.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/mark1foley/Brisbane-Bin-Day-Sensor/pull/1

Commit Summary

  *   a10eb70<https://github.com/mark1foley/Brisbane-Bin-Day-Sensor/pull/1/commits/a10eb703b15b38179ba7b129750ec0dd951e83a1> Update for Opendatasoft platform migration (June 2024)
  *   9d99814<https://github.com/mark1foley/Brisbane-Bin-Day-Sensor/pull/1/commits/9d998141cc06b66ec019d800983f081208196733> Remove unnecessary files
  *   f48850b<https://github.com/mark1foley/Brisbane-Bin-Day-Sensor/pull/1/commits/f48850ba3da85915a78726a55e4099a9548935a1> Fix date format for extra bin query

File Changes

(3 files<https://github.com/mark1foley/Brisbane-Bin-Day-Sensor/pull/1/files>)

  *   M README.md<https://github.com/mark1foley/Brisbane-Bin-Day-Sensor/pull/1/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5> (8)
  *   D custom_components/bne_wc/WCD.csv<https://github.com/mark1foley/Brisbane-Bin-Day-Sensor/pull/1/files#diff-9ce8866ee347af4c85b5989fcca1e06f5b70824e0331ab38f46dac096e880928> (528605)
  *   M custom_components/bne_wc/sensor.py<https://github.com/mark1foley/Brisbane-Bin-Day-Sensor/pull/1/files#diff-f636ac57ae1d880fc3f0829a7134cf143bbdb31a66704fe4177b1a0a68692448> (49)

Patch Links:

  *   https://github.com/mark1foley/Brisbane-Bin-Day-Sensor/pull/1.patch
  *   https://github.com/mark1foley/Brisbane-Bin-Day-Sensor/pull/1.diff

**Pull request merged**
